### ISSUE TITLE
How to import with python 3?

### ISSUE THREAD

**Issue by iCHAIT** [guessit-io/guessit#261]
I am sorry I know its a noob question but I just started working with python 3.

For python 2 -

```from guessit import guess_file_info```

this was working fine.

But now when I try to run the same code in python 3 it gives the following error -

```
Traceback (most recent call last):
from guessit import guess_file_info
ImportError: cannot import name 'guess_file_info'
```

Can someone tell me how to fix this? It would be nice if it would work for both python 2 and 3.

**Comment by Toilal** [comment]
I don't think the issue is related to python 3, but I do think that you have guessit 1.x in python 2 and guessit 2.x in python 3. Since a few day, guessit 2 has been released, so if you want to use guessit 1 now, you have to install it with pip using this command.

```pip3 install "guessit<2"```

Guessit 2 is really better, but requires a migration : http://guessit.readthedocs.org/en/latest/migration.html#migration

**Comment by Toilal** [comment]
In fact docs are not up to date, so for migration you should use docs from github : https://github.com/guessit-io/guessit/blob/master/docs/migration.rst

**Comment by iCHAIT** [comment]
Thanks a lot you were right :)
