### ISSUE TITLE
Multiple titles detected

### ISSUE THREAD

**Issue by ratoaq2** [guessit-io/guessit#309]
`guessit 2.0.5`

I believe this is a bug, since it's the first time that I see multiple titles (and one of them is wrong). All cases where there's more than 1 `title`, guessit uses `alternative_title` (correct me if I'm wrong)

```

guessit -t episode "/Show.Name.S01E05.WEBRip.x264-GROUP__gYDfLA/Show.Name.S01E05.WEBRip.x264-GROUP"
For: /shows/Show.Name.S01E05.WEBRip.x264-GROUP__gYDfLA/Show.Name.S01E05.WEBRip.x264-GROUP
GuessIt found: {
  "title": [
    "Show Name",
    "GROUP gYDfLA"
  ],
  "season": 1,
  "episode": 5,
  "format": "WEBRip",
  "video_codec": "h264",
  "release_group": "GROUP",
  "type": "episode"
}
```

**Comment by Toilal** [comment]
It's actually fixed

```
? /shows/Show.Name.S01E05.WEBRip.x264-GROUP__gYDfLA/Show.Name.S01E05.WEBRip.x264-GROUP
: episode: 5
  format: WEBRip
  release_group: GROUP__gYDfLA
  season: 1
  title: Show Name
  type: episode
  video_codec: h264
```

Matches from `Show.Name.S01E05.WEBRip.x264-GROUP__gYDfLA` filepart are actually returned over `Show.Name.S01E05.WEBRip.x264-GROUP` filepart because it has same matches count but a longer string length.

See [comparators.py](https://github.com/guessit-io/guessit/blob/master/guessit/rules/common/comparators.py#L31-L55)
