### ISSUE TITLE
Incorrect title name

### ISSUE THREAD

**Issue by shlomiLan** [guessit-io/guessit#358]
I'm using V 2.1
When running:

```python
from guessit import guessit
guessit('This.is.Us.S01E01.HDTV.x264-KILLERS.mkv')
```

The result is:

```python
MatchesDict([('title', 'This is'), ('country', <Country [US]>), ('season', 1), ('episode', 1), ('format', 'HDTV'), ('video_codec', 'h264'), ('release_group', 'KILLERS'), ('container', 'mkv'), ('mimetype', 'video/x-matroska'), ('type', 'episode')])
```

the title is set to 'This is' instead of 'This is us'

**Comment by VeNoMouS** [comment]
I came across this tonight with SS-GB, worked out a work around in a couple minutes..

```
>>> from guessit import guessit

>>> guessit('SS-GB.S01E01.1080p.x265-MeGusta.mkv')
MatchesDict([('title', 'SS'), ('country', <Country [GB]>), ('season', 1), ('episode', 1), ('screen_size', '1080p'), ('video_codec', 'h265'), ('release_group', 'MeGusta'), ('container', 'mkv'), ('mimetype', 'video/x-matroska'), ('type', 'episode')])

>>> guessit('SS-GB.S01E01.1080p.x265-MeGusta.mkv', {'allowed_countries':'NONE'})
MatchesDict([('title', 'SS-GB'), ('season', 1), ('episode', 1), ('screen_size', '1080p'), ('video_codec', 'h265'), ('release_group', 'MeGusta'), ('container', 'mkv'), ('mimetype', 'video/x-matroska'), ('type', 'episode')])
>>> 
```

I was using `NONE` as a stupid place holder that would never match...

**Comment by shlomiLan** [comment]
I also see this issue when using version 2.1.4 and trying to make a guess for the
`House.of.Cards.2013.S04E01.720p.WEBRip.X264-DEFLATE.mkv` title
the result that I get is:
`MatchesDict([('title', 'House of Cards'), ('year', 2013), ('season', 4), ('episode', 1), ('screen_size', '720p'), ('format', 'WEBRip'), ('video_codec', 'h264'), ('release_group', 'DEFLATE'), ('container', 'mkv'), ('type', 'episode')])`

But is should be:
`MatchesDict([('title', 'House of Cards'), ('year', 2013), ('season', 4), ('episode', 1), ('screen_size', '720p'), ('format', 'WEBRip'), ('video_codec', 'h264'), ('release_group', 'DEFLATE'), ('container', 'mkv'), ('type', 'episode'), (u'country', u'US')])`

**Comment by ratoaq2** [comment]
Why you should get Country `US`?
This is nowhere in the release name.

**Comment by shlomiLan** [comment]
You right, my bad.
The problem is that there are 2 `House of Cards` shows (US and I think UK) and this one is named in `thetvdb` as `House of Cards (US)` (see [here](http://thetvdb.com/?tab=series&id=262980&lid=7)) so I need this information either in the title as `House of Cards US` or in the `Country` field. Maybe you can apply logic on the show release year that is mentioned in the title (2013)? Is that make sense?

**Comment by ratoaq2** [comment]
This is out of scope for guessit. Guessit is just a release name parser.
Guessit is returning the correct title: `House of Cards` and the correct year `2013`.
It's up to the guessit caller to implement any logic that will look up tv shows information based on names, similar names, aliases, etc.

**Comment by ratoaq2** [comment]
@Toilal 
I have some proposals to enhance Country detection, but they involves case checking.

I saw that there's already a small rule that uses case information:
https://github.com/guessit-io/guessit/blob/develop/guessit/test/movies.yml#L815-L834

Here are some proposals:

Proposal A: Match has mixed case - If the value length is 2 or 3 characters and they have mixed case, discard country (or language) match:
```python
def should_keep(...):
    if len(match.raw) <= 3 and not match.raw.isupper() and not match.raw.islower():
        return False
```

Proposal B: Filepart has mixed case - If the filepart has mixed case (not all lower and not all upper), then discard matches if the value length is 2 or 3 characters and they aren't uppercase.

Proposal B will enhance the detection accuracy for the most common scenarios where the release names have mixed case. `This is us` or `This Is Us` will be correct since only `US` will lead to a country match.

From my point of view, guessit should use all information available to make the guess.

**Comment by VeNoMouS** [comment]
@ratoaq2 can we have a flag to disable country detection all together?

**Comment by ratoaq2** [comment]
This show should be added to `expected_title` in your local guessit configuration

@Toilal, should we still keep guessit internal `expected_title` configuration small? Or should we provide a better default? Since the default config has US enabled, probably this should also be in the default expected title. I'm just re-evaluating each issue.

**Comment by Toilal** [comment]
Hi @ratoaq2, thx for working on guessit for now, I'm too busy right now. No problem to add more weight inside the default configuration, as "This is us" can't be fixed with a smart rule.
