### ISSUE TITLE
Wrong release group + subtitle_language

### ISSUE THREAD

**Issue by IDerr** [guessit-io/guessit#409]
For: [FASubs & TTF] Inuyasha - 099 [DVD] [B15AA1AC].mkv
GuessIt found: {
    "subtitle_language": "Persian",
    "release_group": "& TTF",
    "title": "Inuyasha",
    "season": 0,
    "episode": 99,
    "format": "DVD",
    "crc32": "B15AA1AC",
    "container": "mkv",
    "mimetype": "video/x-matroska",
    "type": "episode"
}

Should be
{
    "release_group": "FASubs & TTF",
    "title": "Inuyasha",
    "episode": 99,
    "format": "DVD",
    "crc32": "B15AA1AC",
    "container": "mkv",
    "mimetype": "video/x-matroska",
    "type": "episode"
}

Thanks a lot

**Comment by ratoaq2** [comment]
Because of this issue #296, all languages are considered by guessit when parsing the release name. This behavior will change in the next major version.

For now you need to restrict which languages you want to be considered. E.g.: `-L en` to use only english. And for animes, it's recommended to use the options `--type episode` / `-t episode` (since it's an episode, not a movie) and `--prefer-episode-number` / `-E` in order to guess absolute episodes (instead of season + episode)

```
guessit -L en -E "[FASubs & TTF] Inuyasha - 099 [DVD] [B15AA1AC].mkv"
For: [FASubs & TTF] Inuyasha - 099 [DVD] [B15AA1AC].mkv
GuessIt found: {
    "release_group": "FASubs & TTF", 
    "title": "Inuyasha", 
    "episode": 99, 
    "format": "DVD", 
    "crc32": "B15AA1AC", 
    "container": "mkv", 
    "mimetype": "video/x-matroska", 
    "type": "episode"
}
```

**Comment by IDerr** [comment]
Thanks for the explanation :D
