### ISSUE TITLE
Guessit ignoring the release group

### ISSUE THREAD

**Issue by duramato** [guessit-io/guessit#569]
The release group should be `SCENE`
```
For: Bones.S03.720p.HDTV.x264-SCENE
GuessIt found: {
    "title": "Bones",
    "season": 3,
    "screen_size": "720p",
    "source": "HDTV",
    "type": "episode"
}
```
```
+-------------------------------------------------------+
+                   GuessIt 3.0.0                       +
+-------------------------------------------------------+
+                   Rebulk 0.9.0                        +
+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|     https://github.com/guessit-io/guessit/issues.     |
+-------------------------------------------------------+
```

**Comment by Toilal** [comment]
It seems to be a bug inside rebulk. I'm investigating.

**Comment by Toilal** [comment]
After more investigation, problem is not in rebulk. the `video_codec` `H.264` is dropped because of [ValidateVideoCodec Rule](https://github.com/guessit-io/guessit/blob/a54e8acdd37ba3fac2be3c651e2d22f8742608c6/guessit/rules/properties/video_codec.py#L73-L94), but it should not ...

Then the release_group is not validated because it's not next a confident property to be guessed as the release group.
