### ISSUE TITLE
Resolution detected as episode title

### ISSUE THREAD

**Issue by duramato** [guessit-io/guessit#572]
```
For: Maniac.S01.400p.GostFilm
GuessIt found: {
    "title": "Maniac",
    "season": 1,
    "episode_title": "400p GostFilm",
    "type": "episode"
}
```

**Comment by duramato** [comment]
@VeNoMouS Clearly that isn't a Scene release, and guessit isn't just for Scene releases.

**Comment by Toilal** [comment]
You may use a custom configuration file to add custom recognized resolutions (`interlaced` and `progressive` entries in `screen_size`).

Default configuration file is [here](https://github.com/guessit-io/guessit/blob/develop/guessit/config/options.json). Docs [here](https://github.com/guessit-io/guessit/blob/develop/docs/advanced-configuration.rst)

This resolution won't be added in default configuration.

**Comment by VeNoMouS** [comment]
@Toilal would be nice to be able to pass the advanced_config as a dict on the options parameter, but reading your code your configure() function pop's the advanced_config and will only load it if forced is true...  but yea... means you have to a config file rather than just dynamically applying it.

ie
```
guessit('Maniac.S01.400p.GostFilm', options={'advanced_config': { 'screen_size': { 'progressive': ["400"]}}})
```

**Comment by Toilal** [comment]
I see @VeNoMouS , please open another issue :+1:
